name: C/C++ CI

on:
  push:
    # branches: [ main ]
    branches: [ branch1 ]
    paths:
        - "SharedMemory"
  pull_request:
    # branches: [ main ]
    branches: [ branch1 ]
    paths:
        - "SharedMemory"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: configure
    #   run: ./configure
    - name: make
      run: make
      working-directory: ./SharedMemory
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
