name: Docker Image CI

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag test_image
    - name: Run Container
      run: docker run -it -d --name test_container -v $(pwd):/workspace test_image
    - name: cd && ls
      run: docker exec test_container /bin/bash -c "cd /workspace && ls"
