name: Docker Image CI

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag my-image-name:$(date +%s)
    - name: Run Container
      run: docker run -v $(pwd):/workspace my-image-name:$(date +%s)
    - name: ls
      run: ls -a
    
