name: Docker Image CI

on:
  push:
    # branches: [ main ]
    branches: [ branch1 ]
    paths:
        - "SharedMemory"
  pull_request:
    # branches: [ main ]
    branches: [ branch1 ]
    paths:
        - "SharedMemory"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag my-image-name:$(date +%s)
